# Generated by Django 5.2.2 on 2025-06-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specs', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='laptops/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bapp.laptopbrand')),
            ],
        ),
    ]
