# Generated by Django 5.2.2 on 2025-07-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0002_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
