# Generated by Django 5.2.2 on 2025-07-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0006_custombuildrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custombuildrequest',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='custombuildrequest',
            old_name='price_quote',
            new_name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='custombuildrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='custombuildrequest',
            name='is_possible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custombuildrequest',
            name='keyboard',
            field=models.CharField(max_length=50),
        ),
    ]
