# Generated by Django 5.2.2 on 2025-07-21 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0007_rename_submitted_at_custombuildrequest_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('delivery_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('cash_option', models.CharField(blank=True, choices=[('pay_on_delivery', 'Pay on Delivery'), ('delivery_online', 'Delivery Online')], max_length=20, null=True)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('is_confirmed_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bapp.laptop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
