# Generated by Django 5.2.2 on 2025-07-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0009_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
