# Generated by Django 5.2.2 on 2025-07-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0011_payment_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='laptop',
        ),
    ]
