# Generated by Django 5.2.2 on 2025-07-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0012_remove_payment_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
