# Generated by Django 5.2.2 on 2025-07-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0013_payment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bapp.laptop'),
        ),
    ]
