# Generated by Django 5.2.2 on 2025-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0014_payment_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='name',
            field=models.CharField(default='unamed', max_length=100),
        ),
    ]
