# Generated by Django 5.2.2 on 2025-07-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0015_laptop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
