# Generated by Django 5.2.2 on 2025-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0016_laptop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Order Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
