# Generated by Django 5.2.2 on 2025-07-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0017_payment_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
