# Generated by Django 5.2.2 on 2025-07-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0019_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='specs',
        ),
        migrations.AddField(
            model_name='laptop',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
