# Generated by Django 5.2.2 on 2025-08-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0023_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='ai_chip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='extra_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='os_type',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Mac', 'Mac'), ('Linux', 'Linux'), ('ERP', 'ERP'), ('Other', 'Other')], default='Windows', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='screen_hertz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
